#pragma once

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_KEYPRESSES
#endif

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
#define RGB_MATRIX_STARTUP_MODE 1
#define RGB_MATRIX_STARTUP_SAT 0
#define RGB_MATRIX_STARTUP_VAL 127
#define RGB_MATRIX_STARTUP_SPD 255
